inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "db/schema.rb"
    - "config/application.rb"
    - "config/environments/**/*"
    - "config/puma.rb"
    - "bin/bundle"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - "Gemfile"

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"
